# Generated by Django 4.2.24 on 2025-09-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastrar_pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('imagem_raca', models.URLField(blank=True, null=True)),
                ('idade', models.IntegerField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cachorros', to='cadastrar_pessoa.pessoa')),
            ],
        ),
    ]
