# Generated by Django 4.2.24 on 2025-09-13 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_cachorro', '0002_alter_cachorro_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachorro',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(20, message='A idade do cachorro não pode ser maior 20 anos, por questão de risco.')]),
        ),
    ]
