# Generated by Django 4.2.24 on 2025-09-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_cachorro', '0003_alter_cachorro_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachorro',
            name='imagem_raca',
        ),
    ]
