# Generated by Django 4.2.24 on 2025-09-13 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_telefone', message='O telefone deve começar com 9 e conter exatamente 9 dígitos.', regex='^9\\d{8}$')])),
            ],
        ),
    ]
